processor:
  ignoreTypes:
    - "(Elasticsearch|Kibana|ApmServer|EnterpriseSearch|Beat)List$"
    - "(Elasticsearch|Kibana|ApmServer|EnterpriseSearch|Beat)Health$"
    - "(Elasticsearch|Kibana|ApmServer|Reconciler|EnterpriseSearch|Beat)Status$"
    - "ElasticsearchSettings$"
    - "Associa(ted|tor|tionStatus|tionConf)$"
  ignoreFields:
    - "status$"
    - "TypeMeta$"

render:
  kubernetesVersion: 1.17
